# General discussion {#discussion}

\vspace*{\fill}\par 
\pagebreak

## Organization of predictive treatment effect heterogeneity literature

### Main findings

We systematically organized the available methodological literature on the
evaluation of treatment effect heterogeneity using the reference class each
method used to define patient similarity. This resulted in the identification of
three separate categories of methods.

Risk-based approaches define patient similarity based solely on risk
factors. These methods can be further divided into risk stratification
approaches that rely on the definition of risk-based subgroups of patients and
risk magnification approaches that assume a constant relative treatment
effect. The latter can be used to make personalized benefit predictions. In
chapter \@ref(sim) the strong assumtion of constant relative treatment effects
was relaxed, allowing for increasingly flexible (**??**) interactions of
baseline risk with treatment. Of course, the assumption that treatment effect is
a function of basline risk remained intact.

Treatment effect modeling methods focus both on risk factors and treatment
effect modifiers to make personalized absolute benefit predictions. These
methods are more intuitive, in the sense that they attempt to account for all
dimensions of treatment effect heterogeneity (**elaborate!!**). However,
statistical power is an important constraint, as multiple treatment-covariate
interaction effects need to be estimated. In the presence of well-documented and
clinically supported effect modifiers statistical power may suffice as only a
small pre-defined set of interaction effects will be evaluated. In more
automated settings, staging or penalization approaches can be considered. The
former rely on the "calibration" of first-stage "working" models including many
treatment-covariate interactions. The latter rely on automated processes that
shrink the estimated interaction effects towards 0.

Finally, optimal treatment rule methods focus on modeling treatment effect
modifiers for the evaluation of treatment effect heterogeneity. Their aim is not
to provide personalized treatment effect estimates or to separate patients into
subgroups of similar expected treatment effect, but rather to separate them into
two categories. Patients who benefit from treatment and patients who do not. If
there are no major treatment-related harms, they can be used out of the box to
guide medical decisions. However, in the presence of serious treatment adverse
events, these methods may be more challenging to implement. That is because the
effect of baseline risk factors is not taken into account. This means that the
baseline risk of the main outcome of interest is not evaluated and, therefore,
the absolute risk reduction achieved with treatment cannot be compared to the
risk increase for the adverse event in question. Also, the clinical relevance of
following the treatment assignment rule cannot be easily evaluated
(**elaborate!!**).

### Other categorization methods in the literature

The above categorization of methods for the assessment of treatment effect
heterogeneity is not the only possible. When focusing on subgroup analyses
[Lipkovich et al](https://onlinelibrary.wiley.com/doi/full/10.1002/sim.7064)
identified two frameworks for personalized medicine: 1) methods that identify
the right patient for a specific treatment and 2) methods that identify the
right treatment for a specific patient. In the first case, a set of treatment
effect modifiers is sought that quantitavely interact with treatment in an
attempt to achieve the highest overall benefit across the entire population. In
the second case, the objective is the idertification of a set of effect
modifiers that qualitatively interact with treatment.

The literature review proposed a general approach for categorizing methods
evaluating treatment effect heterogeneity. However, more thorough separation of
these methods can also be considered. For example in a more technical approach
focusing mainly on tree-based methods,
[Kunzel](https://doi.org/10.1073/pnas.1804597116) separated existing staging
methods into A and S-learners while also suggesting a new approach, the
X-learners. The suggested methods differred in the way they used to recalibrate
the initially derived estimates to estimate conditional average treatment
effects. These suggested categories can be considered as further separation of
treatment effect modeling methods. Assuming binary treatment assignment,
A-learners fit treatment-arm specific models before estimating individualized
treatment effects as their difference. S-learners include treatment assignment
in the development of the tree-based model. They estimate conditional average
treatment effect as the differnce of between setting the treatment indicator to
control and active treatment. Finally, their proposed X-learners, use
first-stage outcome models separately fitted in each treatment arm to impute
coutnerfactual outcomes, thus generating an "observed" treatment effect. Any
regular modeling approach can then be used to estimate treatment effects.

### Limitations

The analyzed literature was identified through a mix of systematic literature
search and suggested literature identified by an expert panel. Though this may
have resulted in a more targeted initial selection of reviewed publications, it
is possible that not all of the targeted literature was captured. However, the
main finding of the review, i.e. a systematic separation of the predictive
methods in the evaluation of treatment effect heterogeneity, should be quite
robust against missing citations. In any way, treatment effect heterogeneity
being a focal point of current research, literature has been growing rapidly
since the presented review was carried out (**need citations??**).

Evaluation of reatment effect heterogeneity is not a problem specific to
healthcare research with important advances being made in economics, social
sciences, and other fields, as well. In addition, the increasing availability of
observational data from massive databases capturing a large proportion of
patients' interaction with the healthcare system has provided additional
challenges, with confounding, suboptimal data capture, local or temporal
inconsistencies only being a few of them. All these have resulted on the
suggestion of many different methods for the evaluation of treatment effect
heterogeneity, many of which may have not been captured in the current literature
review. Our focus was on the clinical trial setting and mainly regression
modeling methods were considered.

### Future research

Several future research goals can be identified. Most importantly, a review of
the fast-growing literature in the observational setting using the suggested
categorization approach needs to be carried out. Due to the added complexity in
this setting (large patient numbers, large number of captured covariates, data
quality issues, and many more) focus has shifted from regression modeling
methods to more automated machine-learning approaches. Therefore, it can be
expected that treatment effect modeling and optimal treatment regime methods are
more prominent in this setting.

In addition, literature search should expand to capture methods suggested in
other research fields. In this way, similar methods developed under different
settings can be unified and transferred among research fields. The
categorization approach suggested can be used to guide this endeavor, while also
it can be further generalized to account for the fundamental differences between
settings.
